<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="89554" started-at="2012-07-31T10:41:24Z" finished-at="2012-07-31T10:42:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="89554" started-at="2012-07-31T10:41:24Z" finished-at="2012-07-31T10:42:53Z">
      <class name="MyExperiments.WebJourney">
        <test-method status="PASS" signature="setUp()[pri:0, instance:MyExperiments.WebJourney@15cda3f]" name="setUp" is-config="true" duration-ms="19721" started-at="2012-07-31T10:41:24Z" finished-at="2012-07-31T10:41:43Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="A_testWebDriverWebJourney1()[pri:0, instance:MyExperiments.WebJourney@15cda3f]" name="A_testWebDriverWebJourney1" duration-ms="44339" started-at="2012-07-31T10:41:43Z" finished-at="2012-07-31T10:42:28Z">
        </test-method> <!-- A_testWebDriverWebJourney1 -->
        <test-method status="FAIL" signature="B_CheckProfile()[pri:0, instance:MyExperiments.WebJourney@15cda3f]" name="B_CheckProfile" duration-ms="810" started-at="2012-07-31T10:42:28Z" finished-at="2012-07-31T10:42:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<IAM ID Verification> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<IAM ID Verification> but was:<true>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at MyExperiments.WebJourney.B_CheckProfile(WebJourney.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- B_CheckProfile -->
        <test-method status="PASS" signature="C_testWebDriverWebJourney2()[pri:0, instance:MyExperiments.WebJourney@15cda3f]" name="C_testWebDriverWebJourney2" duration-ms="6584" started-at="2012-07-31T10:42:29Z" finished-at="2012-07-31T10:42:35Z">
        </test-method> <!-- C_testWebDriverWebJourney2 -->
        <test-method status="PASS" signature="D_testWebDriverWebJourneyEdit()[pri:0, instance:MyExperiments.WebJourney@15cda3f]" name="D_testWebDriverWebJourneyEdit" duration-ms="17933" started-at="2012-07-31T10:42:35Z" finished-at="2012-07-31T10:42:53Z">
        </test-method> <!-- D_testWebDriverWebJourneyEdit -->
        <test-method status="FAIL" signature="E_checkProfile()[pri:0, instance:MyExperiments.WebJourney@15cda3f]" name="E_checkProfile" duration-ms="155" started-at="2012-07-31T10:42:53Z" finished-at="2012-07-31T10:42:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Tenant ID Verification expected:<tnl> but was:<tnl>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Tenant ID Verification expected:<tnl> but was:<tnl>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotSame(Assert.java:485)
	at org.testng.Assert.assertSame(Assert.java:436)
	at MyExperiments.WebJourney.E_checkProfile(WebJourney.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- E_checkProfile -->
      </class> <!-- MyExperiments.WebJourney -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
